language: cpp
sudo: required

install:
  - git clone https://github.com/premake/premake-core.git
  - cd premake-core/
  - git submodule init
  - git submodule update
  - make -f Bootstrap.mak linux
  - cd ..
  - ./premake-core/bin/release/premake5 --file=premake.lua gmake
  - cd workspace/gmake

script: make

compiler:
  - gcc
  
os:
  - linux