# version format
version: 1.0.{build}

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      vsversion: 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      vsversion: 2017

install:
  - if %vsversion%==2015 start /B /W premake/win/premake5 --file=premake.lua vs2015
  - if %vsversion%==2017 start /B /W premake/win/premake5 --file=premake.lua vs2017
      
platform:
  -MSVC 64
  -MSVC 32
  -LLVM 64
  -LLVM 32
  -MSVC ARM
  
matrix:
  exclude:
    - image: Visual Studio 2015
      platform:
        -MSVC ARM64
        -LLVM 64
        -LLVM 32
  
configuration:
  - Release