# version format
version: 1.0.{build}

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      vsversion: 2015
      platform: MSVC 32
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      vsversion: 2015
      platform: MSVC 64
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      vsversion: 2017
      platform: MSVC 32
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      vsversion: 2017
      platform: MSVC 64
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      vsversion: 2017
      platform: LLVM 32
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      vsversion: 2017
      platform: LLVM 64
      configuration: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      vsversion: 2017
      platform: MSVC ARM
      configuration: Release

install:
  - cmd: if %vsversion%==2015
         start /B /W premake/win/premake5 --file=premake.lua vs2015
  - cmd: if %vsversion%==2017
         start /B /W premake/win/premake5 --file=premake.lua vs2017
  - sh: if [[ $APPVEYOR_BUILD_WORKER_IMAGE=Ubuntu ]]
        then
        ./premake/linux/premake5 --file=premake.lua gmake2
        fi
  
#matrix:
#  exclude:
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#      platform: MSVC ARM64